// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_METADATA_GALLERY_H_
#define FLATBUFFERS_GENERATED_METADATA_GALLERY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace gallery {

struct ExifGps;
struct ExifGpsBuilder;

struct Exif;
struct ExifBuilder;

struct Iptc;
struct IptcBuilder;

struct Xmp;
struct XmpBuilder;

struct Metadata;
struct MetadataBuilder;

struct MetadataList;
struct MetadataListBuilder;

struct IsoEntry;
struct IsoEntryBuilder;

struct DateEntry;
struct DateEntryBuilder;

struct CameraEntry;
struct CameraEntryBuilder;

struct TagEntry;
struct TagEntryBuilder;

struct IndexIso;
struct IndexIsoBuilder;

struct IndexDate;
struct IndexDateBuilder;

struct IndexCamera;
struct IndexCameraBuilder;

struct IndexTags;
struct IndexTagsBuilder;

struct ExifGps FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExifGpsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LATITUDE_REF = 4,
    VT_LATITUDE = 6,
    VT_LONGITUDE_REF = 8,
    VT_LONGITUDE = 10,
    VT_ALTITUDE_REF = 12,
    VT_ALTITUDE = 14,
    VT_TIMESTAMP = 16,
    VT_MAP_DATUM = 18
  };
  const ::flatbuffers::String *latitude_ref() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LATITUDE_REF);
  }
  const ::flatbuffers::Vector<double> *latitude() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_LATITUDE);
  }
  const ::flatbuffers::String *longitude_ref() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LONGITUDE_REF);
  }
  const ::flatbuffers::Vector<double> *longitude() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_LONGITUDE);
  }
  uint8_t altitude_ref() const {
    return GetField<uint8_t>(VT_ALTITUDE_REF, 0);
  }
  double altitude() const {
    return GetField<double>(VT_ALTITUDE, 0.0);
  }
  const ::flatbuffers::String *timestamp() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TIMESTAMP);
  }
  const ::flatbuffers::String *map_datum() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAP_DATUM);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LATITUDE_REF) &&
           verifier.VerifyString(latitude_ref()) &&
           VerifyOffset(verifier, VT_LATITUDE) &&
           verifier.VerifyVector(latitude()) &&
           VerifyOffset(verifier, VT_LONGITUDE_REF) &&
           verifier.VerifyString(longitude_ref()) &&
           VerifyOffset(verifier, VT_LONGITUDE) &&
           verifier.VerifyVector(longitude()) &&
           VerifyField<uint8_t>(verifier, VT_ALTITUDE_REF, 1) &&
           VerifyField<double>(verifier, VT_ALTITUDE, 8) &&
           VerifyOffset(verifier, VT_TIMESTAMP) &&
           verifier.VerifyString(timestamp()) &&
           VerifyOffset(verifier, VT_MAP_DATUM) &&
           verifier.VerifyString(map_datum()) &&
           verifier.EndTable();
  }
};

struct ExifGpsBuilder {
  typedef ExifGps Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_latitude_ref(::flatbuffers::Offset<::flatbuffers::String> latitude_ref) {
    fbb_.AddOffset(ExifGps::VT_LATITUDE_REF, latitude_ref);
  }
  void add_latitude(::flatbuffers::Offset<::flatbuffers::Vector<double>> latitude) {
    fbb_.AddOffset(ExifGps::VT_LATITUDE, latitude);
  }
  void add_longitude_ref(::flatbuffers::Offset<::flatbuffers::String> longitude_ref) {
    fbb_.AddOffset(ExifGps::VT_LONGITUDE_REF, longitude_ref);
  }
  void add_longitude(::flatbuffers::Offset<::flatbuffers::Vector<double>> longitude) {
    fbb_.AddOffset(ExifGps::VT_LONGITUDE, longitude);
  }
  void add_altitude_ref(uint8_t altitude_ref) {
    fbb_.AddElement<uint8_t>(ExifGps::VT_ALTITUDE_REF, altitude_ref, 0);
  }
  void add_altitude(double altitude) {
    fbb_.AddElement<double>(ExifGps::VT_ALTITUDE, altitude, 0.0);
  }
  void add_timestamp(::flatbuffers::Offset<::flatbuffers::String> timestamp) {
    fbb_.AddOffset(ExifGps::VT_TIMESTAMP, timestamp);
  }
  void add_map_datum(::flatbuffers::Offset<::flatbuffers::String> map_datum) {
    fbb_.AddOffset(ExifGps::VT_MAP_DATUM, map_datum);
  }
  explicit ExifGpsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ExifGps> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ExifGps>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ExifGps> CreateExifGps(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> latitude_ref = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> latitude = 0,
    ::flatbuffers::Offset<::flatbuffers::String> longitude_ref = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> longitude = 0,
    uint8_t altitude_ref = 0,
    double altitude = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::String> map_datum = 0) {
  ExifGpsBuilder builder_(_fbb);
  builder_.add_altitude(altitude);
  builder_.add_map_datum(map_datum);
  builder_.add_timestamp(timestamp);
  builder_.add_longitude(longitude);
  builder_.add_longitude_ref(longitude_ref);
  builder_.add_latitude(latitude);
  builder_.add_latitude_ref(latitude_ref);
  builder_.add_altitude_ref(altitude_ref);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ExifGps> CreateExifGpsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *latitude_ref = nullptr,
    const std::vector<double> *latitude = nullptr,
    const char *longitude_ref = nullptr,
    const std::vector<double> *longitude = nullptr,
    uint8_t altitude_ref = 0,
    double altitude = 0.0,
    const char *timestamp = nullptr,
    const char *map_datum = nullptr) {
  auto latitude_ref__ = latitude_ref ? _fbb.CreateString(latitude_ref) : 0;
  auto latitude__ = latitude ? _fbb.CreateVector<double>(*latitude) : 0;
  auto longitude_ref__ = longitude_ref ? _fbb.CreateString(longitude_ref) : 0;
  auto longitude__ = longitude ? _fbb.CreateVector<double>(*longitude) : 0;
  auto timestamp__ = timestamp ? _fbb.CreateString(timestamp) : 0;
  auto map_datum__ = map_datum ? _fbb.CreateString(map_datum) : 0;
  return gallery::CreateExifGps(
      _fbb,
      latitude_ref__,
      latitude__,
      longitude_ref__,
      longitude__,
      altitude_ref,
      altitude,
      timestamp__,
      map_datum__);
}

struct Exif FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExifBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAKE = 4,
    VT_MODEL = 6,
    VT_DATETIME = 8,
    VT_COPYRIGHT = 10,
    VT_DATETIME_ORIGINAL = 12,
    VT_GPS = 14
  };
  const ::flatbuffers::String *make() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAKE);
  }
  const ::flatbuffers::String *model() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL);
  }
  const ::flatbuffers::String *datetime() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATETIME);
  }
  const ::flatbuffers::String *copyright() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COPYRIGHT);
  }
  const ::flatbuffers::String *datetime_original() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATETIME_ORIGINAL);
  }
  const gallery::ExifGps *gps() const {
    return GetPointer<const gallery::ExifGps *>(VT_GPS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MAKE) &&
           verifier.VerifyString(make()) &&
           VerifyOffset(verifier, VT_MODEL) &&
           verifier.VerifyString(model()) &&
           VerifyOffset(verifier, VT_DATETIME) &&
           verifier.VerifyString(datetime()) &&
           VerifyOffset(verifier, VT_COPYRIGHT) &&
           verifier.VerifyString(copyright()) &&
           VerifyOffset(verifier, VT_DATETIME_ORIGINAL) &&
           verifier.VerifyString(datetime_original()) &&
           VerifyOffset(verifier, VT_GPS) &&
           verifier.VerifyTable(gps()) &&
           verifier.EndTable();
  }
};

struct ExifBuilder {
  typedef Exif Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_make(::flatbuffers::Offset<::flatbuffers::String> make) {
    fbb_.AddOffset(Exif::VT_MAKE, make);
  }
  void add_model(::flatbuffers::Offset<::flatbuffers::String> model) {
    fbb_.AddOffset(Exif::VT_MODEL, model);
  }
  void add_datetime(::flatbuffers::Offset<::flatbuffers::String> datetime) {
    fbb_.AddOffset(Exif::VT_DATETIME, datetime);
  }
  void add_copyright(::flatbuffers::Offset<::flatbuffers::String> copyright) {
    fbb_.AddOffset(Exif::VT_COPYRIGHT, copyright);
  }
  void add_datetime_original(::flatbuffers::Offset<::flatbuffers::String> datetime_original) {
    fbb_.AddOffset(Exif::VT_DATETIME_ORIGINAL, datetime_original);
  }
  void add_gps(::flatbuffers::Offset<gallery::ExifGps> gps) {
    fbb_.AddOffset(Exif::VT_GPS, gps);
  }
  explicit ExifBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Exif> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Exif>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Exif> CreateExif(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> make = 0,
    ::flatbuffers::Offset<::flatbuffers::String> model = 0,
    ::flatbuffers::Offset<::flatbuffers::String> datetime = 0,
    ::flatbuffers::Offset<::flatbuffers::String> copyright = 0,
    ::flatbuffers::Offset<::flatbuffers::String> datetime_original = 0,
    ::flatbuffers::Offset<gallery::ExifGps> gps = 0) {
  ExifBuilder builder_(_fbb);
  builder_.add_gps(gps);
  builder_.add_datetime_original(datetime_original);
  builder_.add_copyright(copyright);
  builder_.add_datetime(datetime);
  builder_.add_model(model);
  builder_.add_make(make);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Exif> CreateExifDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *make = nullptr,
    const char *model = nullptr,
    const char *datetime = nullptr,
    const char *copyright = nullptr,
    const char *datetime_original = nullptr,
    ::flatbuffers::Offset<gallery::ExifGps> gps = 0) {
  auto make__ = make ? _fbb.CreateString(make) : 0;
  auto model__ = model ? _fbb.CreateString(model) : 0;
  auto datetime__ = datetime ? _fbb.CreateString(datetime) : 0;
  auto copyright__ = copyright ? _fbb.CreateString(copyright) : 0;
  auto datetime_original__ = datetime_original ? _fbb.CreateString(datetime_original) : 0;
  return gallery::CreateExif(
      _fbb,
      make__,
      model__,
      datetime__,
      copyright__,
      datetime_original__,
      gps);
}

struct Iptc FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IptcBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATE_CREATED = 4,
    VT_TIME_CREATED = 6,
    VT_CITY = 8,
    VT_SUB_LOCATION = 10,
    VT_PROVINCE_STATE = 12,
    VT_COUNTRY_CODE = 14,
    VT_COUNTRY_NAME = 16,
    VT_COPYRIGHT = 18
  };
  const ::flatbuffers::String *date_created() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATE_CREATED);
  }
  const ::flatbuffers::String *time_created() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TIME_CREATED);
  }
  const ::flatbuffers::String *city() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CITY);
  }
  const ::flatbuffers::String *sub_location() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SUB_LOCATION);
  }
  const ::flatbuffers::String *province_state() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROVINCE_STATE);
  }
  const ::flatbuffers::String *country_code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNTRY_CODE);
  }
  const ::flatbuffers::String *country_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNTRY_NAME);
  }
  const ::flatbuffers::String *copyright() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COPYRIGHT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATE_CREATED) &&
           verifier.VerifyString(date_created()) &&
           VerifyOffset(verifier, VT_TIME_CREATED) &&
           verifier.VerifyString(time_created()) &&
           VerifyOffset(verifier, VT_CITY) &&
           verifier.VerifyString(city()) &&
           VerifyOffset(verifier, VT_SUB_LOCATION) &&
           verifier.VerifyString(sub_location()) &&
           VerifyOffset(verifier, VT_PROVINCE_STATE) &&
           verifier.VerifyString(province_state()) &&
           VerifyOffset(verifier, VT_COUNTRY_CODE) &&
           verifier.VerifyString(country_code()) &&
           VerifyOffset(verifier, VT_COUNTRY_NAME) &&
           verifier.VerifyString(country_name()) &&
           VerifyOffset(verifier, VT_COPYRIGHT) &&
           verifier.VerifyString(copyright()) &&
           verifier.EndTable();
  }
};

struct IptcBuilder {
  typedef Iptc Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_date_created(::flatbuffers::Offset<::flatbuffers::String> date_created) {
    fbb_.AddOffset(Iptc::VT_DATE_CREATED, date_created);
  }
  void add_time_created(::flatbuffers::Offset<::flatbuffers::String> time_created) {
    fbb_.AddOffset(Iptc::VT_TIME_CREATED, time_created);
  }
  void add_city(::flatbuffers::Offset<::flatbuffers::String> city) {
    fbb_.AddOffset(Iptc::VT_CITY, city);
  }
  void add_sub_location(::flatbuffers::Offset<::flatbuffers::String> sub_location) {
    fbb_.AddOffset(Iptc::VT_SUB_LOCATION, sub_location);
  }
  void add_province_state(::flatbuffers::Offset<::flatbuffers::String> province_state) {
    fbb_.AddOffset(Iptc::VT_PROVINCE_STATE, province_state);
  }
  void add_country_code(::flatbuffers::Offset<::flatbuffers::String> country_code) {
    fbb_.AddOffset(Iptc::VT_COUNTRY_CODE, country_code);
  }
  void add_country_name(::flatbuffers::Offset<::flatbuffers::String> country_name) {
    fbb_.AddOffset(Iptc::VT_COUNTRY_NAME, country_name);
  }
  void add_copyright(::flatbuffers::Offset<::flatbuffers::String> copyright) {
    fbb_.AddOffset(Iptc::VT_COPYRIGHT, copyright);
  }
  explicit IptcBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Iptc> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Iptc>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Iptc> CreateIptc(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> date_created = 0,
    ::flatbuffers::Offset<::flatbuffers::String> time_created = 0,
    ::flatbuffers::Offset<::flatbuffers::String> city = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sub_location = 0,
    ::flatbuffers::Offset<::flatbuffers::String> province_state = 0,
    ::flatbuffers::Offset<::flatbuffers::String> country_code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> country_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> copyright = 0) {
  IptcBuilder builder_(_fbb);
  builder_.add_copyright(copyright);
  builder_.add_country_name(country_name);
  builder_.add_country_code(country_code);
  builder_.add_province_state(province_state);
  builder_.add_sub_location(sub_location);
  builder_.add_city(city);
  builder_.add_time_created(time_created);
  builder_.add_date_created(date_created);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Iptc> CreateIptcDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *date_created = nullptr,
    const char *time_created = nullptr,
    const char *city = nullptr,
    const char *sub_location = nullptr,
    const char *province_state = nullptr,
    const char *country_code = nullptr,
    const char *country_name = nullptr,
    const char *copyright = nullptr) {
  auto date_created__ = date_created ? _fbb.CreateString(date_created) : 0;
  auto time_created__ = time_created ? _fbb.CreateString(time_created) : 0;
  auto city__ = city ? _fbb.CreateString(city) : 0;
  auto sub_location__ = sub_location ? _fbb.CreateString(sub_location) : 0;
  auto province_state__ = province_state ? _fbb.CreateString(province_state) : 0;
  auto country_code__ = country_code ? _fbb.CreateString(country_code) : 0;
  auto country_name__ = country_name ? _fbb.CreateString(country_name) : 0;
  auto copyright__ = copyright ? _fbb.CreateString(copyright) : 0;
  return gallery::CreateIptc(
      _fbb,
      date_created__,
      time_created__,
      city__,
      sub_location__,
      province_state__,
      country_code__,
      country_name__,
      copyright__);
}

struct Xmp FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef XmpBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ADDRESS_ENGLISH = 4,
    VT_ADDRESS_LOCAL = 6,
    VT_COUNTRY_CODE = 8,
    VT_RIGHTS = 10,
    VT_SUBJECT = 12,
    VT_TITLE = 14,
    VT_DATETIME_ORIGINAL = 16,
    VT_CITY = 18,
    VT_COUNTRY = 20,
    VT_STATE = 22,
    VT_PS_COUNTRY_CODE = 24,
    VT_CONTINENT = 26,
    VT_CCA2 = 28,
    VT_CCA3 = 30,
    VT_CAPITAL = 32,
    VT_TIMEZONE = 34,
    VT_COPYRIGHT_OWNER = 36
  };
  const ::flatbuffers::String *address_english() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ADDRESS_ENGLISH);
  }
  const ::flatbuffers::String *address_local() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ADDRESS_LOCAL);
  }
  const ::flatbuffers::String *country_code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNTRY_CODE);
  }
  const ::flatbuffers::String *rights() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RIGHTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *subject() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_SUBJECT);
  }
  const ::flatbuffers::String *title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TITLE);
  }
  const ::flatbuffers::String *datetime_original() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATETIME_ORIGINAL);
  }
  const ::flatbuffers::String *city() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CITY);
  }
  const ::flatbuffers::String *country() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNTRY);
  }
  const ::flatbuffers::String *state() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STATE);
  }
  const ::flatbuffers::String *ps_country_code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PS_COUNTRY_CODE);
  }
  const ::flatbuffers::String *continent() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTINENT);
  }
  const ::flatbuffers::String *cca2() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CCA2);
  }
  const ::flatbuffers::String *cca3() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CCA3);
  }
  const ::flatbuffers::String *capital() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CAPITAL);
  }
  const ::flatbuffers::String *timezone() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TIMEZONE);
  }
  const ::flatbuffers::String *copyright_owner() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COPYRIGHT_OWNER);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ADDRESS_ENGLISH) &&
           verifier.VerifyString(address_english()) &&
           VerifyOffset(verifier, VT_ADDRESS_LOCAL) &&
           verifier.VerifyString(address_local()) &&
           VerifyOffset(verifier, VT_COUNTRY_CODE) &&
           verifier.VerifyString(country_code()) &&
           VerifyOffset(verifier, VT_RIGHTS) &&
           verifier.VerifyString(rights()) &&
           VerifyOffset(verifier, VT_SUBJECT) &&
           verifier.VerifyVector(subject()) &&
           verifier.VerifyVectorOfStrings(subject()) &&
           VerifyOffset(verifier, VT_TITLE) &&
           verifier.VerifyString(title()) &&
           VerifyOffset(verifier, VT_DATETIME_ORIGINAL) &&
           verifier.VerifyString(datetime_original()) &&
           VerifyOffset(verifier, VT_CITY) &&
           verifier.VerifyString(city()) &&
           VerifyOffset(verifier, VT_COUNTRY) &&
           verifier.VerifyString(country()) &&
           VerifyOffset(verifier, VT_STATE) &&
           verifier.VerifyString(state()) &&
           VerifyOffset(verifier, VT_PS_COUNTRY_CODE) &&
           verifier.VerifyString(ps_country_code()) &&
           VerifyOffset(verifier, VT_CONTINENT) &&
           verifier.VerifyString(continent()) &&
           VerifyOffset(verifier, VT_CCA2) &&
           verifier.VerifyString(cca2()) &&
           VerifyOffset(verifier, VT_CCA3) &&
           verifier.VerifyString(cca3()) &&
           VerifyOffset(verifier, VT_CAPITAL) &&
           verifier.VerifyString(capital()) &&
           VerifyOffset(verifier, VT_TIMEZONE) &&
           verifier.VerifyString(timezone()) &&
           VerifyOffset(verifier, VT_COPYRIGHT_OWNER) &&
           verifier.VerifyString(copyright_owner()) &&
           verifier.EndTable();
  }
};

struct XmpBuilder {
  typedef Xmp Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_address_english(::flatbuffers::Offset<::flatbuffers::String> address_english) {
    fbb_.AddOffset(Xmp::VT_ADDRESS_ENGLISH, address_english);
  }
  void add_address_local(::flatbuffers::Offset<::flatbuffers::String> address_local) {
    fbb_.AddOffset(Xmp::VT_ADDRESS_LOCAL, address_local);
  }
  void add_country_code(::flatbuffers::Offset<::flatbuffers::String> country_code) {
    fbb_.AddOffset(Xmp::VT_COUNTRY_CODE, country_code);
  }
  void add_rights(::flatbuffers::Offset<::flatbuffers::String> rights) {
    fbb_.AddOffset(Xmp::VT_RIGHTS, rights);
  }
  void add_subject(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> subject) {
    fbb_.AddOffset(Xmp::VT_SUBJECT, subject);
  }
  void add_title(::flatbuffers::Offset<::flatbuffers::String> title) {
    fbb_.AddOffset(Xmp::VT_TITLE, title);
  }
  void add_datetime_original(::flatbuffers::Offset<::flatbuffers::String> datetime_original) {
    fbb_.AddOffset(Xmp::VT_DATETIME_ORIGINAL, datetime_original);
  }
  void add_city(::flatbuffers::Offset<::flatbuffers::String> city) {
    fbb_.AddOffset(Xmp::VT_CITY, city);
  }
  void add_country(::flatbuffers::Offset<::flatbuffers::String> country) {
    fbb_.AddOffset(Xmp::VT_COUNTRY, country);
  }
  void add_state(::flatbuffers::Offset<::flatbuffers::String> state) {
    fbb_.AddOffset(Xmp::VT_STATE, state);
  }
  void add_ps_country_code(::flatbuffers::Offset<::flatbuffers::String> ps_country_code) {
    fbb_.AddOffset(Xmp::VT_PS_COUNTRY_CODE, ps_country_code);
  }
  void add_continent(::flatbuffers::Offset<::flatbuffers::String> continent) {
    fbb_.AddOffset(Xmp::VT_CONTINENT, continent);
  }
  void add_cca2(::flatbuffers::Offset<::flatbuffers::String> cca2) {
    fbb_.AddOffset(Xmp::VT_CCA2, cca2);
  }
  void add_cca3(::flatbuffers::Offset<::flatbuffers::String> cca3) {
    fbb_.AddOffset(Xmp::VT_CCA3, cca3);
  }
  void add_capital(::flatbuffers::Offset<::flatbuffers::String> capital) {
    fbb_.AddOffset(Xmp::VT_CAPITAL, capital);
  }
  void add_timezone(::flatbuffers::Offset<::flatbuffers::String> timezone) {
    fbb_.AddOffset(Xmp::VT_TIMEZONE, timezone);
  }
  void add_copyright_owner(::flatbuffers::Offset<::flatbuffers::String> copyright_owner) {
    fbb_.AddOffset(Xmp::VT_COPYRIGHT_OWNER, copyright_owner);
  }
  explicit XmpBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Xmp> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Xmp>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Xmp> CreateXmp(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> address_english = 0,
    ::flatbuffers::Offset<::flatbuffers::String> address_local = 0,
    ::flatbuffers::Offset<::flatbuffers::String> country_code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> rights = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> subject = 0,
    ::flatbuffers::Offset<::flatbuffers::String> title = 0,
    ::flatbuffers::Offset<::flatbuffers::String> datetime_original = 0,
    ::flatbuffers::Offset<::flatbuffers::String> city = 0,
    ::flatbuffers::Offset<::flatbuffers::String> country = 0,
    ::flatbuffers::Offset<::flatbuffers::String> state = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ps_country_code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> continent = 0,
    ::flatbuffers::Offset<::flatbuffers::String> cca2 = 0,
    ::flatbuffers::Offset<::flatbuffers::String> cca3 = 0,
    ::flatbuffers::Offset<::flatbuffers::String> capital = 0,
    ::flatbuffers::Offset<::flatbuffers::String> timezone = 0,
    ::flatbuffers::Offset<::flatbuffers::String> copyright_owner = 0) {
  XmpBuilder builder_(_fbb);
  builder_.add_copyright_owner(copyright_owner);
  builder_.add_timezone(timezone);
  builder_.add_capital(capital);
  builder_.add_cca3(cca3);
  builder_.add_cca2(cca2);
  builder_.add_continent(continent);
  builder_.add_ps_country_code(ps_country_code);
  builder_.add_state(state);
  builder_.add_country(country);
  builder_.add_city(city);
  builder_.add_datetime_original(datetime_original);
  builder_.add_title(title);
  builder_.add_subject(subject);
  builder_.add_rights(rights);
  builder_.add_country_code(country_code);
  builder_.add_address_local(address_local);
  builder_.add_address_english(address_english);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Xmp> CreateXmpDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *address_english = nullptr,
    const char *address_local = nullptr,
    const char *country_code = nullptr,
    const char *rights = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *subject = nullptr,
    const char *title = nullptr,
    const char *datetime_original = nullptr,
    const char *city = nullptr,
    const char *country = nullptr,
    const char *state = nullptr,
    const char *ps_country_code = nullptr,
    const char *continent = nullptr,
    const char *cca2 = nullptr,
    const char *cca3 = nullptr,
    const char *capital = nullptr,
    const char *timezone = nullptr,
    const char *copyright_owner = nullptr) {
  auto address_english__ = address_english ? _fbb.CreateString(address_english) : 0;
  auto address_local__ = address_local ? _fbb.CreateString(address_local) : 0;
  auto country_code__ = country_code ? _fbb.CreateString(country_code) : 0;
  auto rights__ = rights ? _fbb.CreateString(rights) : 0;
  auto subject__ = subject ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*subject) : 0;
  auto title__ = title ? _fbb.CreateString(title) : 0;
  auto datetime_original__ = datetime_original ? _fbb.CreateString(datetime_original) : 0;
  auto city__ = city ? _fbb.CreateString(city) : 0;
  auto country__ = country ? _fbb.CreateString(country) : 0;
  auto state__ = state ? _fbb.CreateString(state) : 0;
  auto ps_country_code__ = ps_country_code ? _fbb.CreateString(ps_country_code) : 0;
  auto continent__ = continent ? _fbb.CreateString(continent) : 0;
  auto cca2__ = cca2 ? _fbb.CreateString(cca2) : 0;
  auto cca3__ = cca3 ? _fbb.CreateString(cca3) : 0;
  auto capital__ = capital ? _fbb.CreateString(capital) : 0;
  auto timezone__ = timezone ? _fbb.CreateString(timezone) : 0;
  auto copyright_owner__ = copyright_owner ? _fbb.CreateString(copyright_owner) : 0;
  return gallery::CreateXmp(
      _fbb,
      address_english__,
      address_local__,
      country_code__,
      rights__,
      subject__,
      title__,
      datetime_original__,
      city__,
      country__,
      state__,
      ps_country_code__,
      continent__,
      cca2__,
      cca3__,
      capital__,
      timezone__,
      copyright_owner__);
}

struct Metadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_FILE_PATH = 6,
    VT_EXIF = 8,
    VT_IPTC = 10,
    VT_XMP = 12
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *file_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_PATH);
  }
  const gallery::Exif *exif() const {
    return GetPointer<const gallery::Exif *>(VT_EXIF);
  }
  const gallery::Iptc *iptc() const {
    return GetPointer<const gallery::Iptc *>(VT_IPTC);
  }
  const gallery::Xmp *xmp() const {
    return GetPointer<const gallery::Xmp *>(VT_XMP);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyOffset(verifier, VT_FILE_PATH) &&
           verifier.VerifyString(file_path()) &&
           VerifyOffset(verifier, VT_EXIF) &&
           verifier.VerifyTable(exif()) &&
           VerifyOffset(verifier, VT_IPTC) &&
           verifier.VerifyTable(iptc()) &&
           VerifyOffset(verifier, VT_XMP) &&
           verifier.VerifyTable(xmp()) &&
           verifier.EndTable();
  }
};

struct MetadataBuilder {
  typedef Metadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Metadata::VT_ID, id, 0);
  }
  void add_file_path(::flatbuffers::Offset<::flatbuffers::String> file_path) {
    fbb_.AddOffset(Metadata::VT_FILE_PATH, file_path);
  }
  void add_exif(::flatbuffers::Offset<gallery::Exif> exif) {
    fbb_.AddOffset(Metadata::VT_EXIF, exif);
  }
  void add_iptc(::flatbuffers::Offset<gallery::Iptc> iptc) {
    fbb_.AddOffset(Metadata::VT_IPTC, iptc);
  }
  void add_xmp(::flatbuffers::Offset<gallery::Xmp> xmp) {
    fbb_.AddOffset(Metadata::VT_XMP, xmp);
  }
  explicit MetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Metadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Metadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Metadata> CreateMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> file_path = 0,
    ::flatbuffers::Offset<gallery::Exif> exif = 0,
    ::flatbuffers::Offset<gallery::Iptc> iptc = 0,
    ::flatbuffers::Offset<gallery::Xmp> xmp = 0) {
  MetadataBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_xmp(xmp);
  builder_.add_iptc(iptc);
  builder_.add_exif(exif);
  builder_.add_file_path(file_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Metadata> CreateMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    const char *file_path = nullptr,
    ::flatbuffers::Offset<gallery::Exif> exif = 0,
    ::flatbuffers::Offset<gallery::Iptc> iptc = 0,
    ::flatbuffers::Offset<gallery::Xmp> xmp = 0) {
  auto file_path__ = file_path ? _fbb.CreateString(file_path) : 0;
  return gallery::CreateMetadata(
      _fbb,
      id,
      file_path__,
      exif,
      iptc,
      xmp);
}

struct MetadataList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MetadataListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ITEMS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::Metadata>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::Metadata>> *>(VT_ITEMS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           verifier.EndTable();
  }
};

struct MetadataListBuilder {
  typedef MetadataList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::Metadata>>> items) {
    fbb_.AddOffset(MetadataList::VT_ITEMS, items);
  }
  explicit MetadataListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MetadataList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MetadataList>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MetadataList> CreateMetadataList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::Metadata>>> items = 0) {
  MetadataListBuilder builder_(_fbb);
  builder_.add_items(items);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MetadataList> CreateMetadataListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<gallery::Metadata>> *items = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<gallery::Metadata>>(*items) : 0;
  return gallery::CreateMetadataList(
      _fbb,
      items__);
}

struct IsoEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IsoEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ISO = 4,
    VT_PHOTO_IDS = 6
  };
  uint32_t iso() const {
    return GetField<uint32_t>(VT_ISO, 0);
  }
  const ::flatbuffers::Vector<uint64_t> *photo_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_PHOTO_IDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ISO, 4) &&
           VerifyOffset(verifier, VT_PHOTO_IDS) &&
           verifier.VerifyVector(photo_ids()) &&
           verifier.EndTable();
  }
};

struct IsoEntryBuilder {
  typedef IsoEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_iso(uint32_t iso) {
    fbb_.AddElement<uint32_t>(IsoEntry::VT_ISO, iso, 0);
  }
  void add_photo_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> photo_ids) {
    fbb_.AddOffset(IsoEntry::VT_PHOTO_IDS, photo_ids);
  }
  explicit IsoEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IsoEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IsoEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IsoEntry> CreateIsoEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t iso = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> photo_ids = 0) {
  IsoEntryBuilder builder_(_fbb);
  builder_.add_photo_ids(photo_ids);
  builder_.add_iso(iso);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<IsoEntry> CreateIsoEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t iso = 0,
    const std::vector<uint64_t> *photo_ids = nullptr) {
  auto photo_ids__ = photo_ids ? _fbb.CreateVector<uint64_t>(*photo_ids) : 0;
  return gallery::CreateIsoEntry(
      _fbb,
      iso,
      photo_ids__);
}

struct DateEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DateEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATE = 4,
    VT_PHOTO_IDS = 6
  };
  uint32_t date() const {
    return GetField<uint32_t>(VT_DATE, 0);
  }
  const ::flatbuffers::Vector<uint64_t> *photo_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_PHOTO_IDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_DATE, 4) &&
           VerifyOffset(verifier, VT_PHOTO_IDS) &&
           verifier.VerifyVector(photo_ids()) &&
           verifier.EndTable();
  }
};

struct DateEntryBuilder {
  typedef DateEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_date(uint32_t date) {
    fbb_.AddElement<uint32_t>(DateEntry::VT_DATE, date, 0);
  }
  void add_photo_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> photo_ids) {
    fbb_.AddOffset(DateEntry::VT_PHOTO_IDS, photo_ids);
  }
  explicit DateEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DateEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DateEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DateEntry> CreateDateEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t date = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> photo_ids = 0) {
  DateEntryBuilder builder_(_fbb);
  builder_.add_photo_ids(photo_ids);
  builder_.add_date(date);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DateEntry> CreateDateEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t date = 0,
    const std::vector<uint64_t> *photo_ids = nullptr) {
  auto photo_ids__ = photo_ids ? _fbb.CreateVector<uint64_t>(*photo_ids) : 0;
  return gallery::CreateDateEntry(
      _fbb,
      date,
      photo_ids__);
}

struct CameraEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CameraEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CAMERA_MODEL = 4,
    VT_PHOTO_IDS = 6
  };
  const ::flatbuffers::String *camera_model() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CAMERA_MODEL);
  }
  const ::flatbuffers::Vector<uint64_t> *photo_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_PHOTO_IDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CAMERA_MODEL) &&
           verifier.VerifyString(camera_model()) &&
           VerifyOffset(verifier, VT_PHOTO_IDS) &&
           verifier.VerifyVector(photo_ids()) &&
           verifier.EndTable();
  }
};

struct CameraEntryBuilder {
  typedef CameraEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_camera_model(::flatbuffers::Offset<::flatbuffers::String> camera_model) {
    fbb_.AddOffset(CameraEntry::VT_CAMERA_MODEL, camera_model);
  }
  void add_photo_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> photo_ids) {
    fbb_.AddOffset(CameraEntry::VT_PHOTO_IDS, photo_ids);
  }
  explicit CameraEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CameraEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CameraEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CameraEntry> CreateCameraEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> camera_model = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> photo_ids = 0) {
  CameraEntryBuilder builder_(_fbb);
  builder_.add_photo_ids(photo_ids);
  builder_.add_camera_model(camera_model);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CameraEntry> CreateCameraEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *camera_model = nullptr,
    const std::vector<uint64_t> *photo_ids = nullptr) {
  auto camera_model__ = camera_model ? _fbb.CreateString(camera_model) : 0;
  auto photo_ids__ = photo_ids ? _fbb.CreateVector<uint64_t>(*photo_ids) : 0;
  return gallery::CreateCameraEntry(
      _fbb,
      camera_model__,
      photo_ids__);
}

struct TagEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TagEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TAG = 4,
    VT_PHOTO_IDS = 6
  };
  const ::flatbuffers::String *tag() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TAG);
  }
  const ::flatbuffers::Vector<uint64_t> *photo_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_PHOTO_IDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TAG) &&
           verifier.VerifyString(tag()) &&
           VerifyOffset(verifier, VT_PHOTO_IDS) &&
           verifier.VerifyVector(photo_ids()) &&
           verifier.EndTable();
  }
};

struct TagEntryBuilder {
  typedef TagEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tag(::flatbuffers::Offset<::flatbuffers::String> tag) {
    fbb_.AddOffset(TagEntry::VT_TAG, tag);
  }
  void add_photo_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> photo_ids) {
    fbb_.AddOffset(TagEntry::VT_PHOTO_IDS, photo_ids);
  }
  explicit TagEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TagEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TagEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TagEntry> CreateTagEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> tag = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> photo_ids = 0) {
  TagEntryBuilder builder_(_fbb);
  builder_.add_photo_ids(photo_ids);
  builder_.add_tag(tag);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TagEntry> CreateTagEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *tag = nullptr,
    const std::vector<uint64_t> *photo_ids = nullptr) {
  auto tag__ = tag ? _fbb.CreateString(tag) : 0;
  auto photo_ids__ = photo_ids ? _fbb.CreateVector<uint64_t>(*photo_ids) : 0;
  return gallery::CreateTagEntry(
      _fbb,
      tag__,
      photo_ids__);
}

struct IndexIso FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IndexIsoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::IsoEntry>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::IsoEntry>> *>(VT_ENTRIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct IndexIsoBuilder {
  typedef IndexIso Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::IsoEntry>>> entries) {
    fbb_.AddOffset(IndexIso::VT_ENTRIES, entries);
  }
  explicit IndexIsoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IndexIso> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IndexIso>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IndexIso> CreateIndexIso(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::IsoEntry>>> entries = 0) {
  IndexIsoBuilder builder_(_fbb);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<IndexIso> CreateIndexIsoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<gallery::IsoEntry>> *entries = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<gallery::IsoEntry>>(*entries) : 0;
  return gallery::CreateIndexIso(
      _fbb,
      entries__);
}

struct IndexDate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IndexDateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::DateEntry>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::DateEntry>> *>(VT_ENTRIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct IndexDateBuilder {
  typedef IndexDate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::DateEntry>>> entries) {
    fbb_.AddOffset(IndexDate::VT_ENTRIES, entries);
  }
  explicit IndexDateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IndexDate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IndexDate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IndexDate> CreateIndexDate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::DateEntry>>> entries = 0) {
  IndexDateBuilder builder_(_fbb);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<IndexDate> CreateIndexDateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<gallery::DateEntry>> *entries = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<gallery::DateEntry>>(*entries) : 0;
  return gallery::CreateIndexDate(
      _fbb,
      entries__);
}

struct IndexCamera FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IndexCameraBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::CameraEntry>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::CameraEntry>> *>(VT_ENTRIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct IndexCameraBuilder {
  typedef IndexCamera Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::CameraEntry>>> entries) {
    fbb_.AddOffset(IndexCamera::VT_ENTRIES, entries);
  }
  explicit IndexCameraBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IndexCamera> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IndexCamera>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IndexCamera> CreateIndexCamera(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::CameraEntry>>> entries = 0) {
  IndexCameraBuilder builder_(_fbb);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<IndexCamera> CreateIndexCameraDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<gallery::CameraEntry>> *entries = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<gallery::CameraEntry>>(*entries) : 0;
  return gallery::CreateIndexCamera(
      _fbb,
      entries__);
}

struct IndexTags FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IndexTagsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::TagEntry>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gallery::TagEntry>> *>(VT_ENTRIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct IndexTagsBuilder {
  typedef IndexTags Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::TagEntry>>> entries) {
    fbb_.AddOffset(IndexTags::VT_ENTRIES, entries);
  }
  explicit IndexTagsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IndexTags> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IndexTags>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IndexTags> CreateIndexTags(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gallery::TagEntry>>> entries = 0) {
  IndexTagsBuilder builder_(_fbb);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<IndexTags> CreateIndexTagsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<gallery::TagEntry>> *entries = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<gallery::TagEntry>>(*entries) : 0;
  return gallery::CreateIndexTags(
      _fbb,
      entries__);
}

inline const gallery::MetadataList *GetMetadataList(const void *buf) {
  return ::flatbuffers::GetRoot<gallery::MetadataList>(buf);
}

inline const gallery::MetadataList *GetSizePrefixedMetadataList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<gallery::MetadataList>(buf);
}

inline bool VerifyMetadataListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<gallery::MetadataList>(nullptr);
}

inline bool VerifySizePrefixedMetadataListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<gallery::MetadataList>(nullptr);
}

inline void FinishMetadataListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gallery::MetadataList> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMetadataListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gallery::MetadataList> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace gallery

#endif  // FLATBUFFERS_GENERATED_METADATA_GALLERY_H_
